name: CICDgroupRepo

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, CI/CD!"

      - name: Run npm install
        run: npm install

      - name: Another greeting
        run: echo "Hello, CI/CD again!"
